name: 🐞 Bug
description: Create a report to help us improve
title: "bug:"
labels: ["🐞 bug", "pending"]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is
  validations:
    required: true
- type: textarea
  attributes:
    label: Device Information [optional]
    description: |
      examples:
        - **OS**: Ubuntu 22.04
        - **Swiftwave version**: v1.0.0
        - **Docker version**: 24.0.2
    value: |
        - OS:
        - Swiftwave version:
        - Docker version:
    render: markdown
  validations:
    required: false
- type: dropdown
  attributes:
    label: Are you working on this issue?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true