name: ⭐️ Feature request
description: Suggest an idea for this project
title: "feat:"
labels: ["🌟 feature", "pending"]
body:
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe
    description: A clear and concise description of what the problem is (e.g. I'm always frustrated when [...])
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen
  validations:
    required: true
- type: dropdown
  attributes:
    label: Are you working on this?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true