name: Deploy to Server
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches: [ "main" ]

concurrency:
  group: staging
  cancel-in-progress: true
  
jobs:
  build-production:
    permissions:
      contents: read
      packages: write
    uses: swiftwave-org/SwiftWave/.github/workflows/docker-publish.yml@main

  deploy-production:
    needs: build-production
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
      - name: Delete all cache
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            sudo docker service rm $(sudo docker service ls -q)
            sleep 10
            sudo docker stop $(sudo docker ps -a -q)
            sudo docker rm $(sudo docker ps -a -q)
            sudo docker volume rm $(sudo docker volume ls -q)
            sudo rm -rf /var/lib/docker/*
      - name: Reinstall Swiftwave
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd ~ 
            curl -L get.swiftwave.org | ENVIRONMENT=staging bash

    cleanup-untagged-images:
      uses: swiftwave-org/SwiftWave/.github/workflows/untagged-image-cleanup.yml@main