name: Golang CI
on:
  pull_request:
    branches:
      - develop
      - v1
      - v2
permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    strategy:
      matrix:
        go: ["1.21"]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout 10m
          only-new-issues: true
      - name: Verify dependencies
        run: go mod verify
